/* GENERATED by build.py from site.json -> analytics — do not edit.
   Add or remove a tracking ID there and rebuild; the CSP in _headers,
   the consent categories and the privacy notice all follow from the
   same source and are checked against each other by --check. */
(function () {
  "use strict";

  function loadScript(src) {
    var s = document.createElement("script");
    s.async = true;
    s.src = src;
    document.head.appendChild(s);
  }

  /* Google Consent Mode v2. Denied by default, before any Google
     script exists on the page; KAConsent sends the update. */
  window.dataLayer = window.dataLayer || [];
  window.gtag = function () { window.dataLayer.push(arguments); };
  gtag("consent", "default", {
    ad_storage: "denied",
    ad_user_data: "denied",
    ad_personalization: "denied",
    analytics_storage: "denied",
    personalization_storage: "denied",
    functionality_storage: "granted",
    security_storage: "granted",
    wait_for_update: 500
  });

  KAConsent.onChange(function (consent) {
    gtag("consent", "update", {
      analytics_storage: consent.analytics ? "granted" : "denied",
      ad_storage: consent.marketing ? "granted" : "denied",
      ad_user_data: consent.marketing ? "granted" : "denied",
      ad_personalization: consent.marketing ? "granted" : "denied"
    });
  });

  /* Cookies to clear if a category is refused or withdrawn. */
  KAConsent.forget("analytics", ["_ga", "_ga_*", "_gid", "_gat*"]);

  /* Google Analytics 4 */
  KAConsent.onGrant("analytics", function () {
    loadScript("https://www.googletagmanager.com/gtag/js?id=G-R4QRTNRZKG");
    gtag("js", new Date());
    gtag("config", "G-R4QRTNRZKG");
  });
})();
